server:
  port: 8091
  forward-headers-strategy: framework

spring: 
  application:
    name: department-service
  profiles:
    active:
    - dev   
  

#spring:
#  application:
#    name: department-service
#  output:
#    ansi:
#      enabled: always
#        
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#
##logging:
##  pattern:
##    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"
#
#springdoc:
#  packagesToScan: com.msa.k8s.department
#  cache:
#    disabled: true
#  version: '@springdoc.version@'
#  api-docs:
#    version: openapi-3-1
#
#      
#management:
#  tracing:
#    sampling:
#      probability: 1.0        