#server:
#  port: 8093
#  forward-headers-strategy: framework

spring:
  output:
    ansi:
      enabled: always
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    

springdoc:
  packagesToScan: com.msa.k8s.organization
  cache:
    disabled: true
  version: '@springdoc.version@'
  api-docs:
    version: openapi-3-1

      
management:
  tracing:
    sampling:
      probability: 1.0        